from __future__ import annotations

from pathlib import Path

DEFAULT_MODEL = "base"
DEFAULT_WINDOW_SECONDS = 3.0
DEFAULT_STEP_SECONDS = 0.5
DEFAULT_BUFFER_SECONDS = 30.0
DEFAULT_MIN_AUDIO_SECONDS = 0.5
DEFAULT_BLOCK_DURATION_MS = 100
DEFAULT_ACTIVITY_POLL_SECONDS = 0.25
DEFAULT_ACTIVITY_FRAME_SECONDS = 0.2
DEFAULT_PAUSE_FINALIZE_SECONDS = 0.9
DEFAULT_MIN_SPEECH_SECONDS = 0.35
DEFAULT_UTTERANCE_PADDING_SECONDS = 0.25
DEFAULT_MAX_UTTERANCE_SECONDS = 24.0
DEFAULT_LIVE_TRANSCRIPT = True
DEFAULT_MIN_NEW_CHARS = 8
DEFAULT_DEDUPE_MIN_OVERLAP_CHARS = 20
DEFAULT_DEDUPE_MODE = "lcp"
DEFAULT_STABILITY_WINDOWS = 2
DEFAULT_STABILITY_SIMILARITY_THRESHOLD = 0.86
DEFAULT_RECENT_DUPLICATE_THRESHOLD = 0.82
DEFAULT_MIN_FINAL_WORDS = 3
DEFAULT_MIN_FINAL_CHARS = 12
DEFAULT_SAMPLE_RATE = 16000
DEFAULT_SILENCE_THRESHOLD = 0.003
DEFAULT_MIN_TEXT_LENGTH = 1
DEFAULT_COMPUTE_TYPE = "int8"
DEFAULT_DEVICE_TYPE = "cpu"
DEFAULT_OUTPUT = Path("transcripts/transcript.txt")
DEFAULT_JSONL_OUTPUT = Path("transcripts/transcript.jsonl")
