from __future__ import annotations

from pathlib import Path

DEFAULT_MODEL = "base"
DEFAULT_CHUNK_SECONDS = 6
DEFAULT_SAMPLE_RATE = 48000
DEFAULT_SILENCE_THRESHOLD = 0.003
DEFAULT_MIN_TEXT_LENGTH = 1
DEFAULT_COMPUTE_TYPE = "int8"
DEFAULT_DEVICE_TYPE = "cpu"
DEFAULT_BEAM_SIZE = 1
DEFAULT_FRAME_DURATION_MS = 100
DEFAULT_PAUSE_SECONDS = 0.65
DEFAULT_PRE_ROLL_SECONDS = 0.35
DEFAULT_MIN_SPEECH_SECONDS = 0.25
DEFAULT_MIN_SEGMENT_SECONDS = 0.45
DEFAULT_MAX_SEGMENT_SECONDS = 12.0
DEFAULT_PARTIAL_SECONDS = 2.0
DEFAULT_OUTPUT = Path("transcripts/transcript.txt")
DEFAULT_JSONL_OUTPUT = Path("transcripts/transcript.jsonl")
